name: Build Project
on: [push, pull_request]
jobs:
  build:
    name: Build the Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
        
      - name: Run Clippy
        run: cargo clippy

      - name: Build the Project
        run: cargo build --release

      - name: Upload the built release
        uses: actions/upload-artifact@v3
        with:
          name: ruhroh
          path: target/release/ruhroh